### ISSUE TITLE
String blocks returned with lower case names

### ISSUE THREAD

**Issue by pjs-stockhouse** [Bikeman868/Urchin#5]
If requesting a configuration path to be returned as a string the names are returned in all lower case.  This is a problem for using them in JavaScript code.  Would expect the original case.  Problem appears to be at line 290 of ConfigurationStore.cs:

```
                        var childName = property.Name.ToLower();
                        Children.Add(childName, new ConfigNode(childName, property.Value));
```

**Comment by Bikeman868** [comment]
This issue is fixed in version 1.2.2
