### ISSUE TITLE
When I register with '/' no notifications are received

### ISSUE THREAD

**Issue by rastignacc** [Bikeman868/Urchin#8]
Registering with slash ('/') i.e. to root node doesn't work and notifications aren't received. This is maybe by design but it's a bit misleading as I was going through unit tests and noticed one test which was about solving similar (but not the same as I later found out) problem.

**Comment by Bikeman868** [comment]
The intention was to receive notification of all changes when you register for '/' so this is a bug.
I don't think it will be too hard to fix so i will look into it when I get home this evening.

**Comment by Bikeman868** [comment]
This is fixed in version 1.2.3.
Please verify then close this issue. Thanks.

**Comment by rastignacc** [comment]
This works now. Thanks!
