### ISSUE TITLE
Enum values from configuration JSON can't be properly retrieved using the Get<T>() method

### ISSUE THREAD

**Issue by rastignacc** [Bikeman868/Urchin#9]
When I call ConfigurationSource's Get<T> method with T being an enum exception is thrown with message **Invalid cast from 'System.String' to 'Urchin.Client.Tests.ConfigurationStoreTests+SomeEnum'**

**Comment by rastignacc** [comment]
I've already fixed this in my cloned repo but I'm unable to push bugfix branch I've created on my local so I can open pull request pointing to master.

**Comment by Bikeman868** [comment]
Please submit a pull request. I will verify your fix and merge into the master branch.

**Comment by rastignacc** [comment]
#10 opened

**Comment by Bikeman868** [comment]
For anyone reading this thread, note that Enum values work correctly when you use the recommended approach of registering for configuration changes. This issue only relates to the Get<T>() method that is NOT recommended for general use.

**Comment by Bikeman868** [comment]
This is fixed in version 1.2.4
